---
output:
  xaringan::moon_reader:
    css: "include/aprender.css"
    nature:
      countIncrementalSlides: yes
      highlightLines: yes
      highlightStyle: github
      ratio: 16:9
resource_files:
  - include
  - images
---
class: dark, middle, center
# ""Yo no quiero enseñar **analysis de datos**...""
---
class:regular
# "Yo quiero enseñar..."

--
* Estadística

--
* Biología

--
* Sociología

--
* Finanzas

--
* Diciplina que necesita analizar datos

---
class: dark, middle, center
# "¿Por que estoy aquí?"

---
class:regular
# Necesita herramientas que...

--
* Fácil de empezar a aprender

--
* Fácil de utilizar, y avanzar

--
* Apoyan análisis pequeños y grandes

--
* Habilidades son útiles más alla de la universidad

---
class: dark, middle, center
# ¿Por que **R**?

---
class: regular
# Ventajas de **R**

--
* Lenguaje hecho por, y para estadísticos

--
*  Fácil de aprender

--
*  Comunidad mundial, y amigable

--
*  Integración con otros sistemas

--
*  Es grátis!

---
class: dark, middle, center
# ¿Que cubriremos?

---
class: regular
# Herramientas

--
* R

--
* RStudio

--
* RStudio Cloud

--
* tidyverse

---
class: regular
# Agenda

--
* Hoy - 2 horas - Sesión 1 <br>
**Como usar las herramientas**


--
* Mañana - 2 horas - Sesión 2 <br>
**Como usar las herramientas, para enseñar**
