---
title: "Crear gráficas"
author: "Edgar Ruiz"
date: "Junio 2019"
output:
  xaringan::moon_reader:
    css: "include/aprender.css"
    nature:
      countIncrementalSlides: yes
      highlightLines: yes
      highlightStyle: github
      ratio: 16:9
resource_files:
  - include
  - images
---
```{r, include = FALSE}
library(ggplot2)
```


class: dark, middle, center
# Paquete `ggplot2`

---
class: regular
# Como funciona `ggplot2`

--
* Implementa la **gramática de las gráficas** en **R**

--
* Cualquier gráfica usando: *datos, coordenadas y objetos geométricos (geoms)*

--
* Asignar variables a las **propiedades visuales** 

--
* Se programa por **capas**

---
class:regular
## Capa 1

```{r, fig.height = 5, fig.align = "center"}
ggplot()
```

---
class:regular
## Capa 2

```{r, fig.height = 5, fig.align = "center"}
ggplot() + geom_col(aes(cyl, mpg), data = mtcars)
```

---
class:regular
## Capa 3

```{r, fig.height = 5, fig.align = "center"}
ggplot() + geom_col(aes(cyl, mpg), data = mtcars) + labs(title = "Millas por Galon")
```
